apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupiter-crew-svc
  name: jupiter-crew-svc
  namespace: jupiter
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30100
  selector:
    app: jupiter-crew-svc
  type: NodePort
