apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  namespace: sun
  labels:
    type: worker
spec:
  containers:
    - name: worker-container
      image: busybox
      command: ["sh", "-c", "echo Hello from the runner pod && sleep 3600"]
