apiVersion: v1
kind: Pod
metadata:
  name: secret-handler
  namespace: moon
spec:
  containers:
  - name: secret-handler-pod
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
    - name: secret1_user
      valueFrom:
        secretKeyRef:
          name: secret1
          key: user
    - name: secret1_pass
      valueFrom:
        secretKeyRef:
          name: secret1
          key: pass


