apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: earth
  name: earth-project-earthflower-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
